alias ca='cat' mo='more' inst='sudo apt-fast install -y'
alias l='ls -CFa' cs='cd ..' cl='clear;ls -CFa'
alias gi='git' gdb='gdb -q'
alias py='python' py2='python' py3='python3'
alias gcc-w32='i686-w64-mingw32-gcc'
alias gcc-w64='x86_64-w64-mingw32-gcc'
alias kakao='wine /home/chansol/.wine/drive_c/Program\ Files/Kakao/KakaoTalk/KakaoTalk.exe'
alias cb='chromium-browser'
alias off='shutdown now'
alias inst='sudo apt install -y'
