alias ca='cat' mo='more' inst='sudo apt-fast install -y'
alias l='ls -CFa' cs='cd ..' cl='clear;ls -CFa'
alias gi='git' gdb='gdb -q'
alias py='python' py2='python' py3='python3'
alias gcc-w32='i686-w64-mingw32-gcc'
alias gcc-w64='x86_64-w64-mingw32-gcc'
alias kakao='wine /home/chansol/.wine/drive_c/Program\ Files/Kakao/KakaoTalk/KakaoTalk.exe'
alias cb='nohup chromium-browser'
alias off='shutdown now'
alias inst='sudo apt install -y'
alias gophp='cd /var/www/html' goapa='cd /etc/apache2'
alias godrop='cd /home/kanna/Dropbox'
#alias img='nohup shotwell&'
alias img='img.sh'
alias ocv='ocv.sh'
alias ocvcompile='ocvcompile.sh'
alias opencv="~/.compile_opencv.sh"
alias folder='nohup nautilus&'

alias afreeca_wallmae='nohup streamlink afreecatv.com/ims8868 best&'
alias afreeca_blackwalk='nohup streamlink afreecatv.com/gudcjf604 best&'
alias afreeca_ddedde='nohup streamlink afreecatv.com/seokwngud best&'
alias afreeca_usona='nohup streamlink afreecatv.com/nila25 best&'
alias afreeca_kimchen='nohup streamlink afreecatv.com/rrvv17 best&'
alias afreeca_gamst='nohup streamlink afreecatv.com/devil0108 best&'
alias afreeca_llilka='nohup streamlink afreecatv.com/llilka best&'
alias afreeca_duchi='nohup streamlink afreecatv.com/galsa best&'
alias afreeca_knee='nohup streamlink afreecatv.com/holyknee best&'
alias afreeca_flash='nohup streamlink afreecatv.com/byflash best&'
alias afreeca_yangpang='nohup streamlink afreecatv.com/eunz1nara best&'
alias afreeca_psycopathy='nohup streamlink afreecatv.com/pkdlwpans best&'
alias afreeca_doe='nohup streamlink afreecatv.com/starno1728 best&'
alias afreeca_ceopark='nohup streamlink afreecatv.com/wnstn0905 best&'
alias afreeca_leejisang='nohup streamlink afreecatv.com/jrdart best&'
alias afreeca_teakhwan='nohup streamlink afreecatv.com/goata111789 best&'
alias afreeca_yena='nohup streamlink afreecatv.com/hyn8210 best&'
alias afreeca_chul9='nohup streamlink afreecatv.com/y1026 best&'
alias afreeca_seoyoon='nohup streamlink afreecatv.com/yunheehoho best&'
alias afreeca_ayoon='nohup streamlink afreecatv.com/ayoona best&'
alias afreeca_muse='nohup streamlink afreecatv.com/ppp0000 best&'
alias afreeca_ggaebak='nohup streamlink afreecatv.com/dlghfjs best&'
alias afreeca_jongwook='nohup streamlink afreecatv.com/whddnr2813 best&'
alias afreeca_jd='nohup streamlink afreecatv.com/jaedong23 best&'
alias afreeca_gulza='nohup streamlink afreecatv.com/skswhdkgo best&'
alias afreeca_landing='nohup streamlink afreecatv.com/guslgood2 best&'
alias afreeca_magician='nohup streamlink afreecatv.com/godlife118 best&'
