#!/bin/sh
WINEPREFIX="$HOME/.PlayOnLinux/wineprefix/Office2010" nohup wine $HOME/.PlayOnLinux//wineprefix/Office2010/dosdevices/c:/Program\ Files/Microsoft\ Office/Office14/WINWORD.EXE `mspath $PWD/$1` 2>&1 > /dev/null &
