# Shell variables
# Generated by 'wal'
wallpaper='/home/chansol0505/Pictures/ani/681360.jpg'

# Special
background='#0B1627'
foreground='#dfeaef'
cursor='#dfeaef'

# Colors
color0='#0B1627'
color1='#115D9F'
color2='#2D72AD'
color3='#4C90C4'
color4='#6DC9F0'
color5='#98B2C4'
color6='#A9D8EE'
color7='#dfeaef'
color8='#9ca3a7'
color9='#115D9F'
color10='#2D72AD'
color11='#4C90C4'
color12='#6DC9F0'
color13='#98B2C4'
color14='#A9D8EE'
color15='#dfeaef'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
