--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chansol0505/Pictures/ani/681360.jpg"

-- Special
background="#0B1627"
foreground="#dfeaef"
cursor="#dfeaef"

-- Colors
color0="#0B1627"
color1="#115D9F"
color2="#2D72AD"
color3="#4C90C4"
color4="#6DC9F0"
color5="#98B2C4"
color6="#A9D8EE"
color7="#dfeaef"
color8="#9ca3a7"
color9="#115D9F"
color10="#2D72AD"
color11="#4C90C4"
color12="#6DC9F0"
color13="#98B2C4"
color14="#A9D8EE"
color15="#dfeaef"
